/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-modified_tagged_file_sink_module
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MODIFIED_TAGGED_FILE_SINK_MODULE_API_H
#define INCLUDED_MODIFIED_TAGGED_FILE_SINK_MODULE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_modified_tagged_file_sink_module_EXPORTS
#define MODIFIED_TAGGED_FILE_SINK_MODULE_API __GR_ATTR_EXPORT
#else
#define MODIFIED_TAGGED_FILE_SINK_MODULE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MODIFIED_TAGGED_FILE_SINK_MODULE_API_H */
