find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_MODIFIED_TAGGED_FILE_SINK_MODULE gnuradio-modified_tagged_file_sink_module)

FIND_PATH(
    GR_MODIFIED_TAGGED_FILE_SINK_MODULE_INCLUDE_DIRS
    NAMES gnuradio/modified_tagged_file_sink_module/api.h
    HINTS $ENV{MODIFIED_TAGGED_FILE_SINK_MODULE_DIR}/include
        ${PC_MODIFIED_TAGGED_FILE_SINK_MODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_MODIFIED_TAGGED_FILE_SINK_MODULE_LIBRARIES
    NAMES gnuradio-modified_tagged_file_sink_module
    HINTS $ENV{MODIFIED_TAGGED_FILE_SINK_MODULE_DIR}/lib
        ${PC_MODIFIED_TAGGED_FILE_SINK_MODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-modified_tagged_file_sink_moduleTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_MODIFIED_TAGGED_FILE_SINK_MODULE DEFAULT_MSG GR_MODIFIED_TAGGED_FILE_SINK_MODULE_LIBRARIES GR_MODIFIED_TAGGED_FILE_SINK_MODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_MODIFIED_TAGGED_FILE_SINK_MODULE_LIBRARIES GR_MODIFIED_TAGGED_FILE_SINK_MODULE_INCLUDE_DIRS)
