/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(modified_tagged_file_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5244465f2c7c895515c727fac16fa70f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/modified_tagged_file_sink_module/modified_tagged_file_sink.h>
// pydoc.h is automatically generated in the build directory
#include <modified_tagged_file_sink_pydoc.h>

void bind_modified_tagged_file_sink(py::module& m)
{

    using modified_tagged_file_sink    = gr::modified_tagged_file_sink_module::modified_tagged_file_sink;


    py::class_<modified_tagged_file_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<modified_tagged_file_sink>>(m, "modified_tagged_file_sink", D(modified_tagged_file_sink))

        .def(py::init(&modified_tagged_file_sink::make),
           D(modified_tagged_file_sink,make)
        )
        



        ;




}








